export const categories = [
  "All",
  "Talking Head",
  "Shorts",
  "Promotional",
  "Documentary",
  "Motion Graphics",
  "Explainer",
  "Recreation",
  "Finance",
  "Real Estate",
  "Trading",
  "Education",
  "Social Media",
  "Corporate",
  "Social Media ",
  "Corporate",
  "Personal Branding",
];
