import { VideoProject } from "@/types/videos";

export const videoProjectsData = {
  "75 Hard Challenges on After Effects": [
    {
      id: "S1gb7ugYJO4",
      video_title: "profile",
      video_description: `This video is just create App Ui Animation. It is glassmorphism style animation.`,
      tags: ["", "After Effects"],
      cover_image: "W-L3jCpN7hI",
      publish_date: "2026-01-26",
      client_name: "Naimur Rahman",
      client_image: "/companies/sl-logo.png",
      client_feedback: "",
      video_link: "https://youtu.be/W-L3jCpN7hI",
      project_images: [],
      category: ["75 Hard Challenges on After Effects"],
      duration: "12sec",
      software_used: ["After Effects"],
    },
  ],
  Recreation: [
    {
      id: "Ig1laLcG4ec",
      video_title: "Typography hooks",
      video_description: `This video is just explaining  typography hooks. text based editing with background music.`,
      tags: ["Recreation"],
      cover_image: "Ig1laLcG4ec",
      publish_date: "2025-11-30",
      client_name: "Naimur Rahman",
      client_image: "/companies/sl-logo.png",
      client_feedback: "",
      video_link: "https://youtube.com/shorts/Ig1laLcG4ec",
      project_images: [],
      category: ["Recreation"],
      duration: "30sec",
      software_used: ["Premier pro ", "After Effect"],
    },
  ],

  "Talking Head": [
    {
      id: "S1gb7ugYJO4",
      video_title: "Gig Video ",
      video_description: `.`,
      tags: ["Talking Head", "Explainer"],
      cover_image: "S1gb7ugYJO4",
      publish_date: "2025-12-6",
      client_name: "Naimur Rahman",
      client_image: "/companies/sl-logo.png",
      client_feedback: "",
      video_link: "https://youtu.be/S1gb7ugYJO4?si=40MXHApmPz1g-zzj",
      project_images: [],
      category: ["Talking Head"],
      duration: "1:50",
      software_used: ["Premier pro"],
    },
  ],

  Shorts: [
    {
      id: "DTO99jAijH4",
      video_title: "After Effect Map Pin Animation",
      video_description: `This video is just explaining about After Effect Map Pin Animation.`,
      tags: ["Shorts", "Explainer"],
      cover_image: "DTO99jAijH4",
      publish_date: "2025-11-30",
      client_name: "Naimur Rahman",
      client_image: "/companies/sl-logo.png",
      client_feedback: "",
      video_link: "https://youtu.be/DTO99jAijH4",
      project_images: [],
      category: ["Shorts"],
      duration: "30sec",
      software_used: ["Premier pro ", "After Effect"],
    },

    {
      id: "CGGeIBsuWWU",
      video_title: "As final act of love",
      video_description: `This video is just text based editing with background music.`,
      tags: ["Shorts"],
      cover_image: "CGGeIBsuWWU",
      publish_date: "2025-12-30",
      client_name: "Naimur Rahman",
      client_image: "/companies/sl-logo.png",
      client_feedback: "",
      video_link: "https://youtu.be/CGGeIBsuWWU",
      project_images: [],
      category: ["Shorts"],
      duration: "22sec",
      software_used: ["Premier pro "],
    },

    {
      id: "u56KigbE-mc",
      video_title: "মানুষ আপনার গল্প শুনতে চায়",
      video_description: `.`,
      tags: ["Shorts"],
      cover_image: "u56KigbE-mc",
      publish_date: "2025-10-04",
      client_name: "Naimur Rahman",
      client_image: "/companies/sl-logo.png",
      client_feedback: "",
      video_link: "https://youtube.com/shorts/u56KigbE-mc",
      project_images: [],
      category: ["Shorts"],
      duration: "31sec",
      software_used: ["Premier pro "],
    },
    {
      id: "82k63GhPlpQ",
      video_title: "আমারা ভাই বিলবোর্ড যদি হই  ",
      video_description: `.`,
      tags: ["Shorts"],
      cover_image: "82k63GhPlpQ",
      publish_date: "2025-10-04",
      client_name: "Naimur Rahman",
      client_image: "/companies/sl-logo.png",
      client_feedback: "",
      video_link: "https://youtube.com/shorts/82k63GhPlpQ",
      project_images: [],
      category: ["Shorts"],
      duration: "31sec",
      software_used: ["DaVinci Resolve"],
    },
    {
      id: "Y6FpRcPSIxY",
      video_title: "পথের ফুলের মতোই কিছু মানুষ পথে এসে হাসি দিয়ে যায় ",
      video_description: `.`,
      tags: ["Talking Head", "Explainer"],
      cover_image: "Y6FpRcPSIxY",
      publish_date: "2024-08-04",
      client_name: "Naimur Rahman",
      client_image: "/companies/sl-logo.png",
      client_feedback: "",
      video_link: "https://youtu.be/Y6FpRcPSIxY?si=xxdee_CUanasN5sV",
      project_images: [],
      category: ["Shorts"],
      duration: "6:32",
      software_used: ["DaVinci Resolve"],
    },
  ],
};

export const allVideoProjects: VideoProject[] = [
  // 75 Hard Challenges on After Effects
  {
    id: "a2WEc_VlyW0",
    video_title: "App Ui Animation",
    video_description: `This video is just create App Ui Animation. It is glassmorphism style animation.`,
    tags: ["", "After Effects"],
    cover_image: "W-L3jCpN7hI",
    publish_date: "2026-01-26",
    client_name: "Naimur Rahman",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/W-L3jCpN7hI",
    project_images: [],
    category: ["75 Hard Challenges on After Effects"],
    duration: "12sec",
    software_used: ["After Effects"],
  },
  // 75 Hard Challenges on After Effects

  {
    id: "DTO99jAijH4",
    video_title: "After Effect Map Pin Animation",
    video_description: `This video is just explaining about After Effect Map Pin Animation.`,
    tags: ["Shorts", "Explainer"],
    cover_image: "DTO99jAijH4",
    publish_date: "2025-11-30",
    client_name: "Naimur Rahman",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/DTO99jAijH4",
    project_images: [],
    category: ["Shorts"],
    duration: "30sec",
    software_used: ["Premier pro ", "After Effect"],
  },
  {
    id: "CGGeIBsuWWU",
    video_title: "As final act of love",
    video_description: `This video is just text based editing with background music.`,
    tags: ["Shorts"],
    cover_image: "CGGeIBsuWWU",
    publish_date: "2025-12-30",
    client_name: "Naimur Rahman",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/CGGeIBsuWWU",
    project_images: [],
    category: ["Shorts"],
    duration: "22sec",
    software_used: ["Premier pro "],
  },
  {
    id: "u56KigbE-mc",
    video_title: "মানুষ আপনার গল্প শুনতে চায়",
    video_description: `.`,
    tags: ["Shorts"],
    cover_image: "u56KigbE-mc",
    publish_date: "2025-10-04",
    client_name: "Naimur Rahman",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/u56KigbE-mc",
    project_images: [],
    category: ["Shorts"],
    duration: "31sec",
    software_used: ["Premier pro "],
  },
  {
    id: "82k63GhPlpQ",
    video_title: "আমারা ভাই বিলবোর্ড যদি হই  ",
    video_description: `.`,
    tags: ["Shorts"],
    cover_image: "82k63GhPlpQ",
    publish_date: "2025-10-04",
    client_name: "Naimur Rahman",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/82k63GhPlpQ",
    project_images: [],
    category: ["Shorts"],
    duration: "31sec",
    software_used: ["Premier pro "],
  },
  {
    id: "S1gb7ugYJO4",
    video_title: "Gig Video ",
    video_description: `.`,
    tags: ["Talking Head", "Explainer"],
    cover_image: "S1gb7ugYJO4",
    publish_date: "2025-12-6",
    client_name: "Naimur Rahman",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/S1gb7ugYJO4?si=40MXHApmPz1g-zzj",
    project_images: [],
    category: ["Talking Head"],
    duration: "1:50",
    software_used: ["Premier pro"],
  },
  {
    id: "Y6FpRcPSIxY",
    video_title: "পথের ফুলের মতোই কিছু মানুষ পথে এসে হাসি দিয়ে যায় ",
    video_description: `.`,
    tags: ["Talking Head", "Explainer"],
    cover_image: "Y6FpRcPSIxY",
    publish_date: "2024-08-04",
    client_name: "Naimur Rahman",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/Y6FpRcPSIxY?si=xxdee_CUanasN5sV",
    project_images: [],
    category: ["Shorts", "Explainer"],
    duration: "30sec",
    software_used: ["Premier pro"],
  },
  {
    id: "Ig1laLcG4ec",
    video_title: "Typography hooks",
    video_description: `This video is just explaining  typography hooks. text based editing with background music.`,
    tags: ["Recreation"],
    cover_image: "Ig1laLcG4ec",
    publish_date: "2025-11-30",
    client_name: "Naimur Rahman",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/Ig1laLcG4ec",
    project_images: [],
    category: ["Recreation"],
    duration: "30sec",
    software_used: ["Premier pro ", "After Effect"],
  },
];
