import { VideoProject } from "@/types/videos";

export const videoProjectsData = {
  "Talking Head": [
    {
      id: "W-L3jCpN7hI",
      video_title: "Ready to Take Your Content to the Next Level?",
      video_description: `I help creators, coaches, educators, businesses,
      and personal brands turn raw footage into polished videos that are easy
      to watch, visually engaging, and built around strong storytelling.`,
      tags: ["Video editing", "Video edting services", "Final Cut Pro", "After Effects","Motion Graphics"],
      cover_image: "W-L3jCpN7hI",
      publish_date: "2026-08-24",
      client_name: "Shafiqul Islam",
      client_image: "/client/shafiqul-profile.png",
      client_feedback: "",
      video_link: "https://youtu.be/W-L3jCpN7hI",
      project_images: [],
      category: ["Talking Head",],
      duration: "1:03 min",
      software_used: ["Final Cut Pro","After Effects"],
    },
  ],
  "Talking Head, Finance": [
    {
      id: "veYFPks7baI",
      video_title: "Banks Are in Trouble — Here’s What You Need to Know",
      video_description: `Finance-focused YouTube video about
      a recent Chicago bank failure, edited with clean pacing,
      engaging visuals, B-roll, text animations, and storytelling
      techniques to make financial topics easy to understand.`,
      tags: ["Talking Head", "Finance",],
      cover_image: "veYFPks7baI",
      publish_date: "2026-5-30",
      client_name: "Peter Baker",
      client_image: "/client/peter-baker.jpg",
      client_feedback: "Shafiqul did an amazing job editing my finance video. The pacing, visuals, and storytelling made complex topics easy to understand. Highly recommended!",
      video_link: "https://youtu.be/veYFPks7baI",
      project_images: [],
      category: ["Talking Head", "Finance", "Explainer"],
      duration: "2:42 min",
      software_used: ["Final Cut Pro", "After Effects"],
    },
  ],
  "Talking Head, Real Estate": [
    {
      id: "xmQ9vp4mbBQ",
      video_title: "Are You Buying a Home in Northern Virginia?",
      video_description: `A comprehensive analysis of the current real estate market trends,
      highlighting key factors affecting property values and investment opportunities.`,
      tags: ["Talking Head", "Real Estate", "Market Analysis"],
      cover_image: "xmQ9vp4mbBQ",
      publish_date: "2026-07-15",
      client_name: "Jesse Crosson",
      client_image: "/client/Jesse-Crosson.jpg",
      client_feedback: "The video was insightful and well-edited. It provided a clear understanding of the market trends.",
      video_link: "https://youtu.be/xmQ9vp4mbBQ",
      project_images: [],
      category: ["Talking Head", "Real Estate"],
      duration: "4:05 min",
      software_used: ["Final Cut Pro", "After Effects"],
    },
  ],
  "Talking Head, Trading, Finance": [
    {
      id: "cx8MS85nMvw",
      video_title: "How to Profit From the Risk Others Avoid",
      video_description: `A beginner-friendly guide to trading strategies, covering fundamental concepts,
      market analysis techniques, and practical applications.`,
      tags: ["Talking Head", "Trading", "Finance"],
      cover_image: "cx8MS85nMvw",
      publish_date: "2026-5-20",
      client_name: "Steven Brooks",
      client_image: "/client/Steven-Brooks.jpg",
      client_feedback: "The video was very informative and well-produced. It helped me understand trading strategies better.",
      video_link: "https://youtu.be/cx8MS85nMvw",
      project_images: [],
      category: ["Talking Head", "Trading", "Finance"],
      duration: "3:04 min",
      software_used: ["Final Cut Pro",],
    },
  ],
  "Promotional": [
    {
      id: "J9O19m6sZtQ",
      video_title: "Building E-Commerce Success with 8 Years of Shopify Experience",
      video_description: `A promotional video showcasing the journey and expertise of a successful e-commerce entrepreneur.`,
      tags: ["Promotional", "E-Commerce", "Shopify"],
      cover_image: "J9O19m6sZtQ",
      publish_date: "2026-03-10",
      client_name: "Tasnimul Hassan",
      client_image: "/client/user.png",
      client_feedback: "The promotional video effectively highlighted our brand and services. Great work!",
      video_link: "https://youtu.be/J9O19m6sZtQ",
      project_images: [],
      category: ["Promotional"],
      duration: "59 sec",
      software_used: ["Final Cut Pro"],
    },
  ],
  "Personal Branding, Shorts": [
    {
      id: "Pbf8xduJqJE",
      video_title: "The Power of Personal Branding",
      video_description: `A short-form video emphasizing the importance of personal branding in today's digital landscape.`,
      tags: ["Personal Branding", "Shorts", "Digital Marketing"],
      cover_image: "Pbf8xduJqJE",
      publish_date: "2026-02-15",
      client_name: "Alex Johnson",
      client_image: "/client/user.png",
      client_feedback: "The video captured the essence of personal branding perfectly. It was engaging and informative.",
      video_link: "https://youtu.be/Pbf8xduJqJE",
      project_images: [],
      category: ["Personal Branding", "Shorts"],
      duration: "46 sec",
      software_used: ["Final Cut Pro", "After Effects"],
    },
  ],
};

export const allVideoProjects: VideoProject[] = [
  // Talking Head
  {
    id: "W-L3jCpN7hI",
    video_title: "Ready to Take Your Content to the Next Level?",
    video_description: `I help creators, coaches, educators, businesses,
    and personal brands turn raw footage into polished videos that are easy
    to watch, visually engaging, and built around strong storytelling.`,
    tags: ["Video editing", "Video editing services", "Final Cut Pro", "After Effects","Motion Graphics"],
    cover_image: "W-L3jCpN7hI",
    publish_date: "2026-08-24",
    client_name: "Shafiqul Islam",
    client_image: "/client/shafiqul-profile.png",
    client_feedback: "",
    video_link: "https://youtu.be/W-L3jCpN7hI",
    project_images: [],
    category: ["Talking Head",],
    duration: "1:03 min",
    software_used: ["Final Cut Pro","After Effects"],
  },
  
  // Talking Head, Finance
    {
      id: "veYFPks7baI",
      video_title: "Banks Are in Trouble — Here’s What You Need to Know",
      video_description: `Finance-focused YouTube video about
      a recent Chicago bank failure, edited with clean pacing,
      engaging visuals, B-roll, text animations, and storytelling
      techniques to make financial topics easy to understand.`,
      tags: ["Talking Head", "Finance", "Explainer","Market Analysis","Bank Failure","Financial Crisis"],
      cover_image: "veYFPks7baI",
      publish_date: "2026-5-30",
      client_name: "Peter Baker",
      client_image: "/client/peter-baker.jpg",
      client_feedback: "Shafiqul did an amazing job editing my finance video. The pacing, visuals, and storytelling made complex topics easy to understand. Highly recommended!",
      video_link: "https://youtu.be/veYFPks7baI",
      project_images: [],
      category: ["Talking Head", "Finance",],
      duration: "2:42 min",
      software_used: ["Final Cut Pro", "After Effects"],
    },
  
      //Talking Head, Real Estate
    {
      id: "xmQ9vp4mbBQ",
      video_title: "Are YouBuying a Home in Northern Virginia?",
      video_description: `A comprehensive analysis of the current real estate market trends,
      highlighting key factors affecting property values and investment opportunities.`,
      tags: ["Talking Head", "Real Estate", "Market Analysis"],
      cover_image: "xmQ9vp4mbBQ",
      publish_date: "2026-07-15",
      client_name: "Jesse Crosson",
      client_image: "/client/Jesse-Crosson.jpg",
      client_feedback: "The video was insightful and well-edited. It provided a clear understanding of the market trends.",
      video_link: "https://youtu.be/xmQ9vp4mbBQ",
      project_images: [],
      category: ["Talking Head", "Real Estate"],
      duration: "4:05 min",
      software_used: ["Final Cut Pro", "After Effects"],
    },
    //Talking Head, Trading, Finance
    {
      id: "cx8MS85nMvw",
      video_title: "How to Profit From the Risk Others Avoid",
      video_description: `A beginner-friendly guide to trading strategies, covering fundamental concepts,
      market analysis techniques, and practical applications.`,
      tags: ["Talking Head", "Trading", "Finance"],
      cover_image: "cx8MS85nMvw",
      publish_date: "2026-5-20",
      client_name: "Steven Brooks",
      client_image: "/client/Steven-Brooks.jpg",
      client_feedback: "The video was very informative and well-produced. It helped me understand trading strategies better.",
      video_link: "https://youtu.be/cx8MS85nMvw",
      project_images: [],
      category: ["Talking Head", "Trading", "Finance"],
      duration: "3:04 min",
      software_used: ["Final Cut Pro",],
    },
    //Promotional
    {
      id: "J9O19m6sZtQ",
      video_title: "Building E-Commerce Success with 8 Years of Shopify Experience",
      video_description: `A promotional video showcasing the journey and expertise of a successful e-commerce entrepreneur.`,
      tags: ["Promotional", "E-Commerce", "Shopify"],
      cover_image: "J9O19m6sZtQ",
      publish_date: "2026-03-10",
      client_name: "Tasnimul Hassan",
      client_image: "/client/user.png",
      client_feedback: "The promotional video effectively highlighted our brand and services. Great work!",
      video_link: "https://youtu.be/J9O19m6sZtQ",
      project_images: [],
      category: ["Promotional"],
      duration: "59 sec",
      software_used: ["Final Cut Pro"],
    },
    //Personal Branding, Shorts
    {
      id: "Pbf8xduJqJE",
      video_title: "The Power of Personal Branding",
      video_description: `A short-form video emphasizing the importance of personal branding in today's digital landscape.`,
      tags: ["Personal Branding", "Shorts", "Digital Marketing"],
      cover_image: "Pbf8xduJqJE",
      publish_date: "2026-02-15",
      client_name: "Alex Johnson",
      client_image: "/client/user.png",
      client_feedback: "The video captured the essence of personal branding perfectly. It was engaging and informative.",
      video_link: "https://youtu.be/Pbf8xduJqJE",
      project_images: [],
      category: ["Personal Branding", "Shorts"],
      duration: "46 sec",
      software_used: ["Final Cut Pro", "After Effects"],
    },
];
