import { VideoProject } from "@/types/videos";

export const videoProjectsData = {
  "Talking Head": [
    {
      id: "W-L3jCpN7hI",
      video_title: "Ready to Take Your Content to the Next Level?",
      video_description: `I help creators, coaches, educators, businesses,
      and personal brands turn raw footage into polished videos that are easy
      to watch, visually engaging, and built around strong storytelling.`,
      tags: ["Video editing", "Video edting services", "Final Cut Pro", "After Effects","Motion Graphics"],
      cover_image: "W-L3jCpN7hI",
      publish_date: "2026-08-24",
      client_name: "Shafiqul Islam",
      client_image: "/client/shafiqul-profile.png",
      client_feedback: "",
      video_link: "https://youtu.be/W-L3jCpN7hI",
      project_images: [],
      category: ["Talking Head",],
      duration: "1:03 min",
      software_used: ["Final Cut Pro","After Effects"],
    },
  ],
  "Talking Head, Finance": [
    {
      id: "veYFPks7baI",
      video_title: "Banks Are in Trouble — Here’s What You Need to Know",
      video_description: `Finance-focused YouTube video about
      a recent Chicago bank failure, edited with clean pacing,
      engaging visuals, B-roll, text animations, and storytelling
      techniques to make financial topics easy to understand.`,
      tags: ["Talking Head", "Finance",],
      cover_image: "veYFPks7baI",
      publish_date: "2026-5-30",
      client_name: "Peter Baker",
      client_image: "/client/Peter-Baker.jpg",
      client_feedback: "Shafiqul did an amazing job editing my finance video. The pacing, visuals, and storytelling made complex topics easy to understand. Highly recommended!",
      video_link: "https://youtu.be/veYFPks7baI",
      project_images: [],
      category: ["Talking Head", "Finance", "Explainer"],
      duration: "2:42 min",
      software_used: ["Final Cut Pro", "After Effects"],
    },
  ],
  "Talking Head, Real Estate": [
    {
      id: "xmQ9vp4mbBQ",
      video_title: "Are You Buying a Home in Northern Virginia?",
      video_description: `A comprehensive analysis of the current real estate market trends,
      highlighting key factors affecting property values and investment opportunities.`,
      tags: ["Talking Head", "Real Estate", "Market Analysis"],
      cover_image: "xmQ9vp4mbBQ",
      publish_date: "2026-07-15",
      client_name: "Jesse Crosson",
      client_image: "/client/Jesse-Crosson.jpg",
      client_feedback: "The video was insightful and well-edited. It provided a clear understanding of the market trends.",
      video_link: "https://youtu.be/xmQ9vp4mbBQ",
      project_images: [],
      category: ["Talking Head", "Real Estate"],
      duration: "4:05 min",
      software_used: ["Final Cut Pro", "After Effects"],
    },
  ],
  "Talking Head, Trading, Finance": [
    {
      id: "cx8MS85nMvw",
      video_title: "How to Profit From the Risk Others Avoid",
      video_description: `A beginner-friendly guide to trading strategies, covering fundamental concepts,
      market analysis techniques, and practical applications.`,
      tags: ["Talking Head", "Trading", "Finance"],
      cover_image: "cx8MS85nMvw",
      publish_date: "2026-5-20",
      client_name: "Steven Brooks",
      client_image: "/client/Steven-Brooks.jpg",
      client_feedback: "The video was very informative and well-produced. It helped me understand trading strategies better.",
      video_link: "https://youtu.be/cx8MS85nMvw",
      project_images: [],
      category: ["Talking Head", "Finance"],
      duration: "3:04 min",
      software_used: ["Final Cut Pro",],
    },
  ],
  "Promotional": [
    {
      id: "J9O19m6sZtQ",
      video_title: "Building E-Commerce Success with 8 Years of Shopify Experience",
      video_description: `A promotional video showcasing the journey and expertise of a successful e-commerce entrepreneur.`,
      tags: ["Promotional", "E-Commerce", "Shopify"],
      cover_image: "J9O19m6sZtQ",
      publish_date: "2026-04-10",
      client_name: "Tasnimul Hassan",
      client_image: "/client/user.png",
      client_feedback: "The promotional video effectively highlighted our brand and services. Great work!",
      video_link: "https://youtu.be/J9O19m6sZtQ",
      project_images: [],
      category: ["Promotional", "Talking Head"],
      duration: "59 sec",
      software_used: ["Final Cut Pro"],
    },
  ],
  "Personal Branding, Shorts": [
    {
      id: "Pbf8xduJqJE",
      video_title: "The Power of Personal Branding",
      video_description: `A short-form video emphasizing the importance of personal branding in today's digital landscape.`,
      tags: ["Personal Branding", "Shorts", "Digital Marketing"],
      cover_image: "Pbf8xduJqJE",
      publish_date: "2026-02-15",
      client_name: "Alex Johnson",
      client_image: "/client/user.png",
      client_feedback: "The video captured the essence of personal branding perfectly. It was engaging and informative.",
      video_link: "https://youtu.be/Pbf8xduJqJE",
      project_images: [],
      category: [ "Shorts", "Personal Branding"],
      duration: "46 sec",
      software_used: ["Final Cut Pro", "After Effects"],
    },
  ],
  "Podcast": [
      {
        id: "qE-r68N0lgA",
        video_title: "Why Female Rappers Struggle to Get Signed",
        video_description: `A podcast episode discussing the challenges faced by female rappers in the music industry.`,
        tags: ["Podcast", "Music", "Interview"],
        cover_image: "qE-r68N0lgA",
        publish_date: "2026-04-01",
        client_name: "Maria Rodriguez",
        client_image: "/client/user.png",
        client_feedback: "The podcast was insightful and well-produced. It provided a unique perspective on the music industry.",
        video_link: "https://youtu.be/qE-r68N0lgA",
        project_images: [],
        category: ["Podcast", "Interview"],
        duration: "3:07 min",
        software_used: ["Final Cut Pro",],
      },
    ],
    "Podcast, Interview": [
      {
        id: "g6uOcCrj3iI",
        video_title: "Mickey Factz Reveals the Secret to his Success",
        video_description: `An interview with Mickey Factz, where he shares insights into his creative process and the music industry.`,
        tags: ["Podcast", "Interview", "Music"],
        cover_image: "g6uOcCrj3iI",
        publish_date: "2026-01-10",
        client_name: "Mickey Factz",
        client_image: "/client/user.png",
        client_feedback: "The interview was engaging and provided valuable insights into my music journey.",
        video_link: "https://youtu.be/g6uOcCrj3iI",
        project_images: [],
        category: ["Podcast", "Interview"],
        duration: "6:27 min",
        software_used: ["Final Cut Pro",],
      },
    ],
    "Podcast, Shorts": [
      {
        id: "OHcmebf1OAc",
        video_title: "They clap for my wins but never put in the work",
        video_description: `A short-form podcast clip highlighting the challenges and triumphs of a successful artist.`,
        tags: ["Podcast", "Shorts",],
        cover_image: "OHcmebf1OAc",
        publish_date: "2026-04-10",
        client_name: "2x Cali",
        client_image: "/client/user.png",
        client_feedback: "The short clip was engaging and captured the essence of my message perfectly.",
        video_link: "https://youtu.be/OHcmebf1OAc",
        project_images: [],
        category: ["Podcast", "Shorts"],
        duration: "1:22 min",
        software_used: ["Final Cut Pro",],
      },
    ],
    "Vlog, Challenge, Entertainment, Event": [
      {
        id: "EajmaBNMK6A",
        video_title: "60 Minutes to Make $1,000 — Let the Challenge Begin!",
        video_description: `A thrilling vlog documenting the challenge of making $1,000 in just 60 minutes, showcasing creativity, strategy, and determination.`,
        tags: ["Vlog", "Challenge", "Entertainment", "Event"],
        cover_image: "EajmaBNMK6A",
        publish_date: "2026-06-15",
        client_name: "Ty The Card Guy",
        client_image: "/client/TyTheCardGuy.jpg",
        client_feedback: "The vlog was exciting and kept viewers on the edge of their seats. Great storytelling!",
        video_link: "https://youtu.be/EajmaBNMK6A",
        project_images: [],
        category: ["Vlog", "Entertainment", "Event"],
        duration: "3:41 min",
        software_used: ["Final Cut Pro", "After Effects"],
      },
    ],
    "Talking Head, Health & Wellness": [
      {
        id: "1LLr2eP6bNA",
        video_title: "The mistake that makes tics worse and the technique that stops them",
        video_description: `A YouTube video about tics and how to manage them, edited with clean pacing, engaging visuals, B-roll, text animations, and storytelling techniques to make the topic easy to understand.`,
        tags: ["Talking Head", "Health & Wellness", "Tics", "Mental Health"],
        cover_image: "1LLr2eP6bNA",
        publish_date: "2026-01-10",
        client_name: "Nathan Harison",
        client_image: "/client/NathanPeterson.jpg",
        client_feedback: "The video was very informative and well-produced. It helped me understand how to manage tics better.",
        video_link: "https://youtu.be/1LLr2eP6bNA",
        project_images: [],
        category: ["Talking Head", "Health & Wellness"],
        duration: "3:31 min",
        software_used: ["Final Cut Pro", "After Effects"],
      }
    ],
    "Talking Head, Real Estate, Market Analysis": [
      {
        id: "oKfqAwVY3vw",
        video_title: "Central Virginia Housing Market: What’s Happening in June 2026?",
        video_description: `A YouTube video about the Central Virginia housing market, providing insights into current trends, pricing, and investment opportunities.`,
        tags: ["Talking Head", "Real Estate", "Market Analysis"],
        cover_image: "oKfqAwVY3vw",
        publish_date: "2026-04-15",
        client_name: "Christopher Johnson",
        client_image: "/client/user.png",
        client_feedback: "The video provided a clear and concise overview of the Central Virginia housing market. Very helpful!",
        video_link: "https://youtu.be/oKfqAwVY3vw",
        project_images: [],
        category: ["Talking Head", "Real Estate"],
        duration: "4:12 min",
        software_used: ["Final Cut Pro",],
      }
    ],
    "Law, Shorts": [
      {
        id: "w-u_UFGxrI0",
        video_title: "What types of compensation could receive in car accident?",
        video_description: `A short-form video providing insights into the types of compensation one could receive in a car accident, including medical expenses, lost wages, and pain and suffering.`,
        tags: ["Law", "Short", "Car Accident", "Compensation"],
        cover_image: "w-u_UFGxrI0",
        publish_date: "2026-02-20",
        client_name: "John Doe",
        client_image: "/client/user.png",
        client_feedback: "The video was very informative and provided a clear understanding of the compensation process in car accidents.",
        video_link: "https://youtu.be/w-u_UFGxrI0",
        project_images: [],
        category: ["Law", "Shorts"],
        duration: "30 sec",
        software_used: ["Final Cut Pro",],
      }
    ],
    "Shorts, Finance": [
      {
        id: "qjkU6URRjKY",
        video_title: "3 Ways to Own Silver Without Making Costly Mistakes",
        video_description: `A short-form video providing insights into three ways to own silver without making costly mistakes, including physical silver, ETFs, and mining stocks.`,
        tags: ["Shorts", "Finance", "Silver", "Investing"],
        cover_image: "qjkU6URRjKY",
        publish_date: "2026-03-15",
        client_name: "Ibrahim Khan",
        client_image: "/client/user.png",
        client_feedback: "The video was very informative and provided a clear understanding of the different ways to own silver.",
        video_link: "https://youtu.be/qjkU6URRjKY",
        project_images: [],
        category: ["Shorts", "Finance"],
        duration: "1:03 min",
        software_used: ["Final Cut Pro",],
      }
    ],
    "Finance, Shorts": [
      {
        id: "9aufoNyE6sE",
        video_title: "3 UK specific alternatives to the S&P500",
        video_description: `A short-form video providing insights into three UK-specific alternatives to the S&P500, including FTSE 100, FTSE 250, and AIM.`,
        tags: ["Finance", "Shorts", "Investing"],
        cover_image: "9aufoNyE6sE",
        publish_date: "2026-01-20",
        client_name: "Ibrahim Khan",
        client_image: "/client/user.png",
        client_feedback: "The video was very informative and provided a clear understanding of the different UK-specific alternatives to the S&P500.",
        video_link: "https://youtu.be/9aufoNyE6sE",
        project_images: [],
        category: ["Finance", "Shorts"],
        duration: "1:08 min",
        software_used: ["Final Cut Pro",],
      }
    ],
    "Shorts, Consistency": [
        {
        id: "mOGfNph2fWE",
        video_title: "The Power of Showing Up Every Day",
        video_description: `A short-form video emphasizing the importance of consistency and showing up every day to achieve success.`,
        tags: ["Shorts", "Consistency", "Motivation"],
        cover_image: "mOGfNph2fWE",
        publish_date: "2026-02-10",
        client_name: "Sharon Lee",
        client_image: "/client/user.png",
        client_feedback: "The video was very motivating and provided a clear understanding of the power of consistency.",
        video_link: "https://youtu.be/mOGfNph2fWE",
        project_images: [],
        category: ["Shorts"],
        duration: "28 sec",
        software_used: ["Final Cut Pro",],
      }
    ],
      "Shorts, Video Editing": [
        {
          id: "1jNewtJZBYQ",
          video_title: "A Good Editor Knows the Right Ingredients",
          video_description: `A short-form video emphasizing the importance of having the right ingredients for successful video editing.`,
          tags: ["Shorts", "Video Editing", "Tips"],
          cover_image: "1jNewtJZBYQ",
          publish_date: "2026-03-05",
          client_name: "David Kim",
          client_image: "/client/user.png",
          client_feedback: "The video was very informative and provided a clear understanding of the right ingredients for successful video editing.",
          video_link: "https://youtu.be/1jNewtJZBYQ",
          project_images: [],
          category: ["Shorts",],
          duration: "11 sec",
          software_used: ["Final Cut Pro",],
        }
      ],
      "Shorts, Tips": [
        {
          id: "gOnxBoXW3H0",
          video_title: "Perfect Results Come From Consistent Effort",
          video_description: `A short-form video emphasizing the importance of consistent effort in achieving perfect results.`,
          tags: ["Shorts", "Tips", "Motivation"],
          cover_image: "gOnxBoXW3H0",
          publish_date: "2026-02-01",
          client_name: "Emily Davis",
          client_image: "/client/user.png",
          client_feedback: "The video was very motivating and provided a clear understanding of the importance of consistent effort.",
          video_link: "https://youtu.be/gOnxBoXW3H0",
          project_images: [],
          category: ["Shorts",],
          duration: "11 sec",
          software_used: ["Final Cut Pro", "After Effects"],
        }
      ],
      "Vlog, Event": [
        {
          id: "u9GvSsFYXNA",
          video_title: "Inside the Toronto Sport Card Expo | Full Show Experience",
          video_description: `A vlog providing an inside look at the Toronto Sport Card Expo, showcasing the full show experience, including interviews, product showcases, and event highlights.`,
          tags: ["Vlog", "Event", "Toronto Sport Card Expo"],
          cover_image: "u9GvSsFYXNA",
          publish_date: "2026-05-20",
          client_name: "Ty The Card Guy",
          client_image: "/client/TyTheCardGuy.jpg",
          client_feedback: "The vlog provided a comprehensive overview of the Toronto Sport Card Expo. It was engaging and informative.",
          video_link: "https://youtu.be/u9GvSsFYXNA",
          project_images: [],
          category: ["Vlog", "Event"],
          duration: "3:49 min",
          software_used: ["Final Cut Pro", "After Effects"],
        }
      ],
      "Finance, Talking Head": [
        {
          id: "rcsW7ukRM8U",
          video_title: "How I Turned Quitting My Job Into a $190M Business",
          video_description: `A finance-focused YouTube video about turning the decision to quit a job into a successful business venture, edited with clean pacing, engaging visuals, B-roll, text animations, and storytelling techniques to make financial topics easy to understand.`,
          tags: ["Finance", "Talking Head", "Entrepreneurship"],
          cover_image: "rcsW7ukRM8U",
          publish_date: "2026-01-10",
          client_name: "Ibrahim Khan",
          client_image: "/client/user.png",
          client_feedback: "The video was very informative and well-produced. It provided valuable insights into entrepreneurship and business growth.",
          video_link: "https://youtu.be/rcsW7ukRM8U",
          project_images: [],
          category: ["Finance", "Talking Head"],
          duration: "5:25 min",
          software_used: ["Final Cut Pro", "After Effects"],
        }
      ],
};

//--------------------------------------------------------------------------------------------------------------

export const allVideoProjects: VideoProject[] = [
  // Talking Head
  {
    id: "W-L3jCpN7hI",
    video_title: "Ready to Take Your Content to the Next Level?",
    video_description: `I help creators, coaches, educators, businesses,
    and personal brands turn raw footage into polished videos that are easy
    to watch, visually engaging, and built around strong storytelling.`,
    tags: ["Video editing", "Video editing services", "Final Cut Pro", "After Effects","Motion Graphics"],
    cover_image: "W-L3jCpN7hI",
    publish_date: "2026-08-24",
    client_name: "Shafiqul Islam",
    client_image: "/client/shafiqul-profile.png",
    client_feedback: "",
    video_link: "https://youtu.be/W-L3jCpN7hI",
    project_images: [],
    category: ["Talking Head",],
    duration: "1:03 min",
    software_used: ["Final Cut Pro","After Effects"],
  },
  
  // Talking Head, Finance
    {
      id: "veYFPks7baI",
      video_title: "Banks Are in Trouble — Here’s What You Need to Know",
      video_description: `Finance-focused YouTube video about
      a recent Chicago bank failure, edited with clean pacing,
      engaging visuals, B-roll, text animations, and storytelling
      techniques to make financial topics easy to understand.`,
      tags: ["Talking Head", "Finance", "Explainer","Market Analysis","Bank Failure","Financial Crisis"],
      cover_image: "veYFPks7baI",
      publish_date: "2026-5-30",
      client_name: "Peter Baker",
      client_image: "/client/peter-baker.jpg",
      client_feedback: "Shafiqul did an amazing job editing my finance video. The pacing, visuals, and storytelling made complex topics easy to understand. Highly recommended!",
      video_link: "https://youtu.be/veYFPks7baI",
      project_images: [],
      category: ["Talking Head", "Finance",],
      duration: "2:42 min",
      software_used: ["Final Cut Pro", "After Effects"],
    },
  
      //Talking Head, Real Estate
    {
      id: "xmQ9vp4mbBQ",
      video_title: "Are YouBuying a Home in Northern Virginia?",
      video_description: `A comprehensive analysis of the current real estate market trends,
      highlighting key factors affecting property values and investment opportunities.`,
      tags: ["Talking Head", "Real Estate", "Market Analysis"],
      cover_image: "xmQ9vp4mbBQ",
      publish_date: "2026-07-15",
      client_name: "Jesse Crosson",
      client_image: "/client/Jesse-Crosson.jpg",
      client_feedback: "The video was insightful and well-edited. It provided a clear understanding of the market trends.",
      video_link: "https://youtu.be/xmQ9vp4mbBQ",
      project_images: [],
      category: ["Talking Head", "Real Estate"],
      duration: "4:05 min",
      software_used: ["Final Cut Pro", "After Effects"],
    },
    //Talking Head, Trading, Finance
    {
      id: "cx8MS85nMvw",
      video_title: "How to Profit From the Risk Others Avoid",
      video_description: `A beginner-friendly guide to trading strategies, covering fundamental concepts,
      market analysis techniques, and practical applications.`,
      tags: ["Talking Head", "Trading", "Finance"],
      cover_image: "cx8MS85nMvw",
      publish_date: "2026-5-20",
      client_name: "Steven Brooks",
      client_image: "/client/Steven-Brooks.jpg",
      client_feedback: "The video was very informative and well-produced. It helped me understand trading strategies better.",
      video_link: "https://youtu.be/cx8MS85nMvw",
      project_images: [],
      category: ["Talking Head", "Finance"],
      duration: "3:04 min",
      software_used: ["Final Cut Pro",],
    },
    //Promotional
    {
      id: "J9O19m6sZtQ",
      video_title: "Building E-Commerce Success with 8 Years of Shopify Experience",
      video_description: `A promotional video showcasing the journey and expertise of a successful e-commerce entrepreneur.`,
      tags: ["Promotional", "E-Commerce", "Shopify"],
      cover_image: "J9O19m6sZtQ",
      publish_date: "2026-04-10",
      client_name: "Tasnimul Hassan",
      client_image: "/client/user.png",
      client_feedback: "The promotional video effectively highlighted our brand and services. Great work!",
      video_link: "https://youtu.be/J9O19m6sZtQ",
      project_images: [],
      category: ["Promotional", "Talking Head"],
      duration: "59 sec",
      software_used: ["Final Cut Pro"],
    },
    //Personal Branding, Shorts
    {
      id: "Pbf8xduJqJE",
      video_title: "The Power of Personal Branding",
      video_description: `A short-form video emphasizing the importance of personal branding in today's digital landscape.`,
      tags: ["Personal Branding", "Shorts", "Digital Marketing"],
      cover_image: "Pbf8xduJqJE",
      publish_date: "2026-02-15",
      client_name: "Alex Johnson",
      client_image: "/client/user.png",
      client_feedback: "The video captured the essence of personal branding perfectly. It was engaging and informative.",
      video_link: "https://youtu.be/Pbf8xduJqJE",
      project_images: [],
      category: [ "Shorts", "Personal Branding"],
      duration: "46 sec",
      software_used: ["Final Cut Pro", "After Effects"],
    },
    //Podcast
    {
      id: "qE-r68N0lgA",
      video_title: "Why Female Rappers Struggle to Get Signed",
      video_description: `A podcast episode discussing the challenges faced by female rappers in the music industry.`,
      tags: ["Podcast", "Music", "Interview"],
      cover_image: "qE-r68N0lgA",
      publish_date: "2026-04-01",
      client_name: "Maria Rodriguez",
      client_image: "/client/user.png",
      client_feedback: "The podcast was insightful and well-produced. It provided a unique perspective on the music industry.",
      video_link: "https://youtu.be/qE-r68N0lgA",
      project_images: [],
      category: ["Podcast", "Interview"],
      duration: "3:07 min",
      software_used: ["Final Cut Pro",],
    },
    //Podcast, Interview
      {
        id: "g6uOcCrj3iI",
        video_title: "Mickey Factz Reveals the Secret to his Success",
        video_description: `An interview with Mickey Factz, where he shares insights into his creative process and the music industry.`,
        tags: ["Podcast", "Interview", "Music"],
        cover_image: "g6uOcCrj3iI",
        publish_date: "2026-01-10",
        client_name: "Mickey Factz",
        client_image: "/client/user.png",
        client_feedback: "The interview was engaging and provided valuable insights into my music journey.",
        video_link: "https://youtu.be/g6uOcCrj3iI",
        project_images: [],
        category: ["Podcast", "Interview"],
        duration: "6:27 min",
        software_used: ["Final Cut Pro",],
      },
      //Podcast, Shorts
      {
        id: "OHcmebf1OAc",
        video_title: "They clap for my wins but never put in the work",
        video_description: `A short-form podcast clip highlighting the challenges and triumphs of a successful artist.`,
        tags: ["Podcast", "Shorts",],
        cover_image: "OHcmebf1OAc",
        publish_date: "2026-04-10",
        client_name: "2x Cali",
        client_image: "/client/user.png",
        client_feedback: "The short clip was engaging and captured the essence of my message perfectly.",
        video_link: "https://youtu.be/OHcmebf1OAc",
        project_images: [],
        category: ["Podcast", "Shorts"],
        duration: "1:22 min",
        software_used: ["Final Cut Pro",],
      },
      //Vlog, Challenge, Entertainment, Event
      {
        id: "EajmaBNMK6A",
        video_title: "60 Minutes to Make $1,000 — Let the Challenge Begin!",
        video_description: `A thrilling vlog documenting the challenge of making $1,000 in just 60 minutes, showcasing creativity, strategy, and determination.`,
        tags: ["Vlog", "Challenge", "Entertainment", "Event"],
        cover_image: "EajmaBNMK6A",
        publish_date: "2026-06-15",
        client_name: "Ty The Card Guy",
        client_image: "/client/TyTheCardGuy.jpg",
        client_feedback: "The vlog was exciting and kept viewers on the edge of their seats. Great storytelling!",
        video_link: "https://youtu.be/EajmaBNMK6A",
        project_images: [],
        category: ["Vlog", "Entertainment", "Event"],
        duration: "3:41 min",
        software_used: ["Final Cut Pro", "After Effects"],
      },
      //Talking Head, Health & Wellness
      {
        id: "1LLr2eP6bNA",
        video_title: "The mistake that makes tics worse and the technique that stops them",
        video_description: `A YouTube video about tics and how to manage them, edited with clean pacing, engaging visuals, B-roll, text animations, and storytelling techniques to make the topic easy to understand.`,
        tags: ["Talking Head", "Health & Wellness", "Tics", "Mental Health"],
        cover_image: "1LLr2eP6bNA",
        publish_date: "2026-01-10",
        client_name: "Nathan Harison",
        client_image: "/client/NathanPeterson.jpg",
        client_feedback: "The video was very informative and well-produced. It helped me understand how to manage tics better.",
        video_link: "https://youtu.be/1LLr2eP6bNA",
        project_images: [],
        category: ["Talking Head", "Health & Wellness"],
        duration: "3:31 min",
        software_used: ["Final Cut Pro", "After Effects"],
      },
      //Talking Head, Real Estate, Market Analysis"
      {
        id: "oKfqAwVY3vw",
        video_title: "Central Virginia Housing Market: What’s Happening in June 2026?",
        video_description: `A YouTube video about the Central Virginia housing market, providing insights into current trends, pricing, and investment opportunities.`,
        tags: ["Talking Head", "Real Estate", "Market Analysis"],
        cover_image: "oKfqAwVY3vw",
        publish_date: "2026-04-15",
        client_name: "Christopher Johnson",
        client_image: "/client/user.png",
        client_feedback: "The video provided a clear and concise overview of the Central Virginia housing market. Very helpful!",
        video_link: "https://youtu.be/oKfqAwVY3vw",
        project_images: [],
        category: ["Talking Head", "Real Estate"],
        duration: "4:12 min",
        software_used: ["Final Cut Pro",],
      },
      //Law, Shorts
      {
        id: "w-u_UFGxrI0",
        video_title: "What types of compensation could receive in car accident?",
        video_description: `A short-form video providing insights into the types of compensation one could receive in a car accident, including medical expenses, lost wages, and pain and suffering.`,
        tags: ["Law", "Short", "Car Accident", "Compensation"],
        cover_image: "w-u_UFGxrI0",
        publish_date: "2026-02-20",
        client_name: "John Doe",
        client_image: "/client/user.png",
        client_feedback: "The video was very informative and provided a clear understanding of the compensation process in car accidents.",
        video_link: "https://youtu.be/w-u_UFGxrI0",
        project_images: [],
        category: ["Law", "Shorts"],
        duration: "30 sec",
        software_used: ["Final Cut Pro",],
      },
      //Shorts, Finance
      {
        id: "qjkU6URRjKY",
        video_title: "3 Ways to Own Silver Without Making Costly Mistakes",
        video_description: `A short-form video providing insights into three ways to own silver without making costly mistakes, including physical silver, ETFs, and mining stocks.`,
        tags: ["Shorts", "Finance", "Silver", "Investing"],
        cover_image: "qjkU6URRjKY",
        publish_date: "2026-03-15",
        client_name: "Ibrahim Khan",
        client_image: "/client/user.png",
        client_feedback: "The video was very informative and provided a clear understanding of the different ways to own silver.",
        video_link: "https://youtu.be/qjkU6URRjKY",
        project_images: [],
        category: ["Shorts", "Finance"],
        duration: "1:03 min",
        software_used: ["Final Cut Pro",],
      },
      //Finance, Shorts
      {
        id: "9aufoNyE6sE",
        video_title: "3 UK specific alternatives to the S&P500",
        video_description: `A short-form video providing insights into three UK-specific alternatives to the S&P500, including FTSE 100, FTSE 250, and AIM.`,
        tags: ["Finance", "Shorts", "Investing"],
        cover_image: "9aufoNyE6sE",
        publish_date: "2026-01-20",
        client_name: "Ibrahim Khan",
        client_image: "/client/user.png",
        client_feedback: "The video was very informative and provided a clear understanding of the different UK-specific alternatives to the S&P500.",
        video_link: "https://youtu.be/9aufoNyE6sE",
        project_images: [],
        category: ["Finance", "Shorts"],
        duration: "1:08 min",
        software_used: ["Final Cut Pro",],
      },
      //Shorts, Consistency
        {
          id: "mOGfNph2fWE",
          video_title: "The Power of Showing Up Every Day",
          video_description: `A short-form video emphasizing the importance of consistency and showing up every day to achieve success.`,
          tags: ["Shorts", "Consistency", "Motivation"],
          cover_image: "mOGfNph2fWE",
          publish_date: "2026-02-10",
          client_name: "Sharon Lee",
          client_image: "/client/user.png",
          client_feedback: "The video was very motivating and provided a clear understanding of the power of consistency.",
          video_link: "https://youtu.be/mOGfNph2fWE",
          project_images: [],
          category: ["Shorts"],
          duration: "28 sec",
          software_used: ["Final Cut Pro",],
        },
          //Shorts, Video Editing
        {
          id: "1jNewtJZBYQ",
          video_title: "A Good Editor Knows the Right Ingredients",
          video_description: `A short-form video emphasizing the importance of having the right ingredients for successful video editing.`,
          tags: ["Shorts", "Video Editing", "Tips"],
          cover_image: "1jNewtJZBYQ",
          publish_date: "2026-03-05",
          client_name: "David Kim",
          client_image: "/client/user.png",
          client_feedback: "The video was very informative and provided a clear understanding of the right ingredients for successful video editing.",
          video_link: "https://youtu.be/1jNewtJZBYQ",
          project_images: [],
          category: ["Shorts",],
          duration: "11 sec",
          software_used: ["Final Cut Pro",],
        },
        //Shorts, Tips
        {
          id: "gOnxBoXW3H0",
          video_title: "Perfect Results Come From Consistent Effort",
          video_description: `A short-form video emphasizing the importance of consistent effort in achieving perfect results.`,
          tags: ["Shorts", "Tips", "Motivation"],
          cover_image: "gOnxBoXW3H0",
          publish_date: "2026-02-01",
          client_name: "Emily Davis",
          client_image: "/client/user.png",
          client_feedback: "The video was very motivating and provided a clear understanding of the importance of consistent effort.",
          video_link: "https://youtu.be/gOnxBoXW3H0",
          project_images: [],
          category: ["Shorts",],
          duration: "11 sec",
          software_used: ["Final Cut Pro", "After Effects"],
        },
        //Vlog, Event
        {
          id: "u9GvSsFYXNA",
          video_title: "Inside the Toronto Sport Card Expo | Full Show Experience",
          video_description: `A vlog providing an inside look at the Toronto Sport Card Expo, showcasing the full show experience, including interviews, product showcases, and event highlights.`,
          tags: ["Vlog", "Event", "Toronto Sport Card Expo"],
          cover_image: "u9GvSsFYXNA",
          publish_date: "2026-05-20",
          client_name: "Ty The Card Guy",
          client_image: "/client/TyTheCardGuy.jpg",
          client_feedback: "The vlog provided a comprehensive overview of the Toronto Sport Card Expo. It was engaging and informative.",
          video_link: "https://youtu.be/u9GvSsFYXNA",
          project_images: [],
          category: ["Vlog", "Event"],
          duration: "3:49 min",
          software_used: ["Final Cut Pro", "After Effects"],
        },
        //Finance, Talking Head
        {
          id: "rcsW7ukRM8U",
          video_title: "How I Turned Quitting My Job Into a $190M Business",
          video_description: `A finance-focused YouTube video about turning the decision to quit a job into a successful business venture, edited with clean pacing, engaging visuals, B-roll, text animations, and storytelling techniques to make financial topics easy to understand.`,
          tags: ["Finance", "Talking Head", "Entrepreneurship"],
          cover_image: "rcsW7ukRM8U",
          publish_date: "2026-01-10",
          client_name: "Ibrahim Khan",
          client_image: "/client/user.png",
          client_feedback: "The video was very informative and well-produced. It provided valuable insights into entrepreneurship and business growth.",
          video_link: "https://youtu.be/rcsW7ukRM8U",
          project_images: [],
          category: ["Finance", "Talking Head"],
          duration: "5:25 min",
          software_used: ["Final Cut Pro", "After Effects"],
        }
];
